apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-news-deployment
spec:
  # replicas: 1
  template:
    metadata:
      name: db-news
      labels:
        app: db-news
    spec:
      containers:
        - name: db-news-container
          image: aluracursos/mysql-db:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: db-configmap  
          # livenessProbe:   # not recommended, here the container has a database, test fail.
          #   httpGet:
          #     path: /
          #     port: 80
          #   periodSeconds: 10
          #   failureThreshold: 3
          #   initialDelaySeconds: 20
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          #   periodSeconds: 10
          #   failureThreshold: 10
          #   initialDelaySeconds: 20
  selector:
    matchLabels:
      app: db-news