apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: news-sistem-statefulset
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: news-sistem
      name: news-sistem
    spec:
      containers:
        - name: news-sistem-container
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: sistem-configmap
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /inserir_noticias.php
              port: 80
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          volumeMounts:
            - name: images
              mountPath: /var/www/html/uploads
            - name: session
              mountPath: /tmp
      volumes:
        - name: images
          persistentVolumeClaim:
            claimName: images-pvc
        - name: session
          persistentVolumeClaim:
            claimName: session-pvc
  selector:
    matchLabels:
      app: news-sistem
  serviceName: svc-news-sistem